var json2go = function() {
  var obj = {
    tabSize: 4,
    structs: [],
    renderObject: function(object) {
      var children = [];
      var type = this.renderObjectInternal("AutoGeneratedStruct", undefined, object);
      children.push(this.getDeserializeFunction(type));
      children.push(this.getSerializeFunction(type));
      children.push(this.structs)
      return this.getPackage("autogenerated", children);
    },
    renderObjectInternal: function(type, key, object) {
      var outer = this;
      var children = [];

      if (object == null || object == undefined) {
        return "interface{}";
      } else if (typeof(object) == 'string') {
        return "string";
      } else if (typeof(object) == 'number') {
        return outer.isInt(object) ? "int64" : "float64";
      } else if (typeof(object) == 'boolean') {
        return "bool";
      } else if (object.constructor == Array) {
        return "[]"+outer.renderObjectInternal(outer.getTypeName(type, key), key, object[0])
      } else if (object.constructor == Object) {
        if (Object.keys(object).length === 0) {
          return "interface{}";
        }

        Object.keys(object).forEach(function eachKey(innerKey) {
          var innerType = outer.renderObjectInternal(outer.getTypeName(type, innerKey), innerKey, object[innerKey])
          children.push(outer.getProperty(innerKey, innerType));
        });
      }

      this.structs.push(this.getStruct(type, children));
      return type;
    },
    isInt: function(n) {
      return n % 1 === 0;
    },
    getTypeName: function(prefix, type) {
      if (type == "") {
        return prefix+"Empty";
      }
      return prefix+this.getPascalCase(type);
    },
    getPropertyName: function(type) {
      if (type == "") {
        return "Empty";
      }
      return this.sanitizeTypeName(this.getPascalCase(type));
    },
    sanitizeTypeName: function(type) {
      if (!isNaN(type) || type.match(/^\d/)) {
        type = "Num"+type;
      }

      return type;
    },
    getPackage: function(name, children) {
      var rendered = `package ${name}\n\n`
      rendered +=    `import "encoding/json"\n\n`;
      rendered +=    children.join('\n\n')

      return rendered;
    },
    getStruct: function(type, children) {
      var rendered =  `type ${type} struct {\n`;
      rendered +=     children.join('\n')
      rendered +=     `\n}`

      return rendered;
    },
    getProperty: function(key, type) {
      var indentation = this.getIndentation();
      var rendered = "";
      rendered +=  `${indentation}${this.getPropertyName(key)} ${type}`
      if (key != undefined) {
        rendered += ` \`json:"${key}"\``
      }

      return rendered;
    },
    getPascalCase: function(str) {
      if (str == undefined) {return ""}
      return str.toLowerCase().replace(/(?:(^.)|([-_\s]+.))/g, function(match) {
        return match.charAt(match.length-1).toUpperCase();
      })
    },
    getIndentation: function(depth) {
      var tab = ' '.repeat(this.tabSize);
      if (depth > 1) {
        return tab.repeat(depth);
      }

      return tab;
    },
    getDeserializeFunction: function(type) {
      var indentation = this.getIndentation();
      var rendered =  `func Deserialize(str string) ${type} {\n`
      rendered +=     `${indentation}var t ${type}\n`
      rendered +=     `${indentation}json.Unmarshal([]byte(str), &t)\n`
      rendered +=     `${indentation}return t\n`
      rendered +=     `}`
      
      return rendered
    },
    getSerializeFunction: function(type) {
      var indentation = this.getIndentation();
      var rendered =  `func Serialize(t ${type}) string {\n`
      rendered +=     `${indentation}json, _ := json.Marshal(t)\n`
      rendered +=     `${indentation}return string(json)\n`
      rendered +=     `}`

      return rendered
    }
  }

  return obj;
}
